file(READ "${INPUT}" source)
foreach(kind IN ITEMS zero missing overflow)
  set(mutated "${source}")
  if(kind STREQUAL "zero")
    string(REPLACE "attention.cpu.kv_capacity_tokens = 512 : i64," "attention.cpu.kv_capacity_tokens = 0 : i64," mutated "${mutated}")
  elseif(kind STREQUAL "missing")
    string(REPLACE "attention.cpu.kv_capacity_tokens = 512 : i64," "" mutated "${mutated}")
  else()
    string(REPLACE "attention.cpu.kv_capacity_tokens = 512 : i64," "attention.cpu.kv_capacity_tokens = 9223372036854775807 : i64," mutated "${mutated}")
  endif()
  set(path "${OUT_DIR}/contiguous_kv_${kind}.mlir")
  file(WRITE "${path}" "${mutated}")
  execute_process(COMMAND "${TOOL}" --device-profile "${PROFILE}" --mlir "${path}" --out "${OUT_DIR}/contiguous_kv_${kind}.json" RESULT_VARIABLE rc)
  if(rc EQUAL 0)
    message(FATAL_ERROR "illegal contiguous KV capacity unexpectedly compiled: ${kind}")
  endif()
endforeach()
