#!/usr/bin/env python3
"""generate_tile_candidate_harness.py

Generates three C++ test/benchmark tools for the AArch64 tile-candidate
slice from candidate_results.json's static candidate list (42 (shape,
tile) pairs, each compiled to a UNIQUE _mlir_ciface_ symbol -- see
generate_aarch64_matmul_tile_candidates.py's renamed_fixture() for why a
per-candidate symbol rename was required for this to link into one
process).

Generated (all written under mlir_passes/tools/, all project-owned,
non-handwritten-NEON test/benchmark code -- same convention as every prior
harness in this repo):
  - aarch64_matmul_tile_candidate_repeated_call_test.cpp
  - aarch64_matmul_tile_candidate_mixed_stress_test.cpp
  - aarch64_matmul_tile_candidate_benchmark.cpp

Usage:
  python3 tools/generate_tile_candidate_harness.py \
    --candidates /tmp/tile_candidate_static_results.json \
    --output-dir mlir_passes/tools
"""
import argparse
import json


HEADER_COMMON = """// {fname}
//
// GENERATED by tools/generate_tile_candidate_harness.py from
// candidate_results.json -- do not hand-edit the dispatch table; rerun the
// generator if the candidate set changes. See that script and
// artifacts/backend_codegen/aarch64_matmul_bias_relu_tile_candidates/README.md
// for the full tile-candidate slice context.
//
// {purpose}

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <string>
#include <vector>
"""

COMMON_DECLS = """
extern "C" {
struct MemRef2D {
  float* allocated;
  float* aligned;
  int64_t offset;
  int64_t sizes[2];
  int64_t strides[2];
};
"""

COMMON_HELPERS = """
using GeneratedFn = void (*)(MemRef2D*, MemRef2D*, MemRef2D*, MemRef2D*);

namespace {

struct Candidate {
  int64_t m, n, k;
  int tm, tn, tk;
  GeneratedFn fn;
  std::string shapeKey;
  std::string tileKey;
};

void fillDeterministic(float* p, int64_t n, uint32_t seed) {
  uint32_t state = seed;
  for (int64_t i = 0; i < n; ++i) {
    state = state * 1664525u + 1013904223u;
    p[i] = static_cast<float>((state >> 8) & 0xFFFFu) / 65536.0f - 0.5f;
  }
}

void scalarRef(const float* lhs, const float* rhs, const float* bias, float* out,
               int64_t M, int64_t N, int64_t K) {
  for (int64_t i = 0; i < M; ++i) {
    for (int64_t j = 0; j < N; ++j) {
      float acc = 0.0f;
      for (int64_t k = 0; k < K; ++k) acc += lhs[i * K + k] * rhs[k * N + j];
      float v = acc + bias[i * N + j];
      out[i * N + j] = v > 0.0f ? v : 0.0f;
    }
  }
}

MemRef2D makeDescriptor(float* payload, int64_t rows, int64_t cols) {
  MemRef2D d{};
  d.allocated = payload;
  d.aligned = payload;
  d.offset = 0;
  d.sizes[0] = rows;
  d.sizes[1] = cols;
  d.strides[0] = cols;
  d.strides[1] = 1;
  return d;
}

}  // namespace
"""


def candidate_extern_decls(candidates):
    lines = []
    for c in candidates:
        lines.append(f"void {c['ciface_symbol']}(MemRef2D*, MemRef2D*, MemRef2D*, MemRef2D*);")
    return "\n".join(lines)


def candidate_table_entries(candidates):
    lines = []
    for c in candidates:
        m, n, k = c["shape"]
        tm, tn, tk = c["tile"]["m"], c["tile"]["n"], c["tile"]["k"]
        shape_key = f"{m}x{n}x{k}"
        tile_key = f"tm{tm}_tn{tn}_tk{tk}"
        lines.append(
            f'  table.push_back(Candidate{{{m}, {n}, {k}, {tm}, {tn}, {tk}, '
            f'{c["ciface_symbol"]}, "{shape_key}", "{tile_key}"}});'
        )
    return "\n".join(lines)


def gen_repeated_call_test(candidates):
    body = HEADER_COMMON.format(
        fname="aarch64_matmul_tile_candidate_repeated_call_test.cpp",
        purpose=(
            "Repeated-call correctness + guard-region regression test for every\n"
            "// AArch64 tile candidate. Usage:\n"
            "//   ./aarch64_matmul_tile_candidate_repeated_call_test <shape MxNxK> <tile tmM_tnN_tkK> <num_calls>\n"
            "// Guard regions follow the same convention as\n"
            "// aarch64_matmul_bias_relu_repeated_call_test.cpp: sentinel-filled\n"
            "// prefix/suffix around every caller-owned buffer, bit-exact comparison\n"
            "// (not float ==/!=, which false-positives on identical NaN bit patterns)."
        ),
    )
    body += COMMON_DECLS
    body += candidate_extern_decls(candidates)
    body += "\n}\n"
    body += COMMON_HELPERS
    body += """
namespace {

constexpr int64_t kGuardElems = 64;
constexpr uint32_t kSentinelBits = 0xDEADBEEFu;

float sentinelValue(int index) {
  uint32_t bits = kSentinelBits ^ static_cast<uint32_t>(index * 2654435761u);
  float f;
  std::memcpy(&f, &bits, sizeof(f));
  return f;
}

struct GuardedBuffer {
  std::vector<float> storage;
  int64_t payloadElems;
  explicit GuardedBuffer(int64_t elems) : storage(static_cast<size_t>(elems + 2 * kGuardElems)), payloadElems(elems) {
    for (int64_t i = 0; i < kGuardElems; ++i) {
      storage[static_cast<size_t>(i)] = sentinelValue(static_cast<int>(i));
      storage[static_cast<size_t>(kGuardElems + payloadElems + i)] = sentinelValue(static_cast<int>(1000 + i));
    }
  }
  float* payload() { return storage.data() + kGuardElems; }
  static bool bitsEqual(float a, float b) {
    uint32_t ba, bb;
    std::memcpy(&ba, &a, sizeof(ba));
    std::memcpy(&bb, &b, sizeof(bb));
    return ba == bb;
  }
  int checkGuards() {
    for (int64_t i = 0; i < kGuardElems; ++i) {
      if (!bitsEqual(storage[static_cast<size_t>(i)], sentinelValue(static_cast<int>(i))))
        return static_cast<int>(i - kGuardElems);
    }
    for (int64_t i = 0; i < kGuardElems; ++i) {
      size_t idx = static_cast<size_t>(kGuardElems + payloadElems + i);
      if (!bitsEqual(storage[idx], sentinelValue(static_cast<int>(1000 + i))))
        return static_cast<int>(payloadElems + i);
    }
    return -1;
  }
};

std::vector<Candidate> buildTable() {
  std::vector<Candidate> table;
""" + candidate_table_entries(candidates) + """
  return table;
}

}  // namespace

namespace {

// Returns true if this (shape, tile) passed both the 1-call and numCalls
// repeated-call check, printing a PASS/FAIL line either way.
bool runOne(const Candidate& c, int64_t numCalls) {
  int64_t M = c.m, N = c.n, K = c.k;
  GuardedBuffer lhsBuf(M * K), rhsBuf(K * N), biasBuf(M * N);
  fillDeterministic(lhsBuf.payload(), M * K, 0x1234u + static_cast<uint32_t>(M));
  fillDeterministic(rhsBuf.payload(), K * N, 0x5678u + static_cast<uint32_t>(N));
  fillDeterministic(biasBuf.payload(), M * N, 0x9abcu + static_cast<uint32_t>(K));

  std::vector<float> ref(static_cast<size_t>(M * N));
  scalarRef(lhsBuf.payload(), rhsBuf.payload(), biasBuf.payload(), ref.data(), M, N, K);

  MemRef2D lhsDesc = makeDescriptor(lhsBuf.payload(), M, K);
  MemRef2D rhsDesc = makeDescriptor(rhsBuf.payload(), K, N);
  MemRef2D biasDesc = makeDescriptor(biasBuf.payload(), M, N);

  int64_t firstFail = -1;
  for (int64_t call = 0; call < numCalls; ++call) {
    MemRef2D out{};
    c.fn(&out, &lhsDesc, &rhsDesc, &biasDesc);

    bool descOk = out.sizes[0] == M && out.sizes[1] == N && out.strides[0] == N &&
                  out.strides[1] == 1 && out.offset == 0 && out.allocated != nullptr &&
                  out.aligned != nullptr;
    double maxErr = 0.0;
    for (int64_t i = 0; i < M * N; ++i) {
      maxErr = std::max(maxErr, static_cast<double>(std::fabs(out.aligned[i] - ref[static_cast<size_t>(i)])));
    }
    bool outputOk = maxErr < 1e-3;
    int lhsGuard = lhsBuf.checkGuards();
    int rhsGuard = rhsBuf.checkGuards();
    int biasGuard = biasBuf.checkGuards();
    bool guardsOk = (lhsGuard == -1 && rhsGuard == -1 && biasGuard == -1);

    if (!descOk || !outputOk || !guardsOk) {
      firstFail = call;
      std::printf("FAIL: shape=%s tile=%s calls=%lld call=%lld descOk=%d outputOk=%d (maxErr=%.6f) guardsOk=%d (lhs=%d rhs=%d bias=%d)\\n",
                  c.shapeKey.c_str(), c.tileKey.c_str(), (long long)numCalls, (long long)call, descOk, outputOk, maxErr, guardsOk,
                  lhsGuard, rhsGuard, biasGuard);
      std::free(out.allocated);
      break;
    }
    std::free(out.allocated);
  }

  if (firstFail == -1) {
    std::printf("PASS: shape=%s tile=%s all %lld calls correct, guards clean\\n",
                c.shapeKey.c_str(), c.tileKey.c_str(), (long long)numCalls);
    return true;
  }
  std::printf("FAIL: shape=%s tile=%s first failure at call %lld / %lld\\n",
              c.shapeKey.c_str(), c.tileKey.c_str(), (long long)firstFail, (long long)numCalls);
  return false;
}

}  // namespace

int main(int argc, char** argv) {
  // No args: run 1-call then <repeated_calls> for EVERY candidate in one
  // process (minimizes SSH round trips for the Pi integration script).
  // With args: run just one (shape, tile) pair, for targeted debugging.
  int64_t repeatedCalls = argc > 3 ? std::atoll(argv[3]) : (argc > 1 ? std::atoll(argv[1]) : 1000);
  std::vector<Candidate> table = buildTable();

  if (argc >= 3 && std::string(argv[1]).find('x') != std::string::npos) {
    std::string shapeKey = argv[1];
    std::string tileKey = argv[2];
    int64_t numCalls = argc > 3 ? std::atoll(argv[3]) : 1000;
    const Candidate* found = nullptr;
    for (const auto& c : table) {
      if (c.shapeKey == shapeKey && c.tileKey == tileKey) { found = &c; break; }
    }
    if (found == nullptr) {
      std::fprintf(stderr, "unknown (shape, tile): %s %s\\n", shapeKey.c_str(), tileKey.c_str());
      return 2;
    }
    return runOne(*found, numCalls) ? 0 : 1;
  }

  int64_t numCalls = argc > 1 ? std::atoll(argv[1]) : 1000;
  bool allOk = true;
  for (const auto& c : table) {
    allOk &= runOne(c, 1);
    allOk &= runOne(c, numCalls);
  }
  std::printf(allOk ? "OVERALL: PASS (%zu candidates, 1-call + %lld-call each)\\n"
                     : "OVERALL: FAIL\\n", table.size(), (long long)numCalls);
  return allOk ? 0 : 1;
}
"""
    return body


def gen_mixed_stress_test(candidates):
    body = HEADER_COMMON.format(
        fname="aarch64_matmul_tile_candidate_mixed_stress_test.cpp",
        purpose=(
            "Mixed-candidate, same-process stress test. Cycles through the exact\n"
            "// sequence given in the tile-candidate task brief:\n"
            "//   16x16x16 tile 4x4x4, 32x32x32 tile 4x8x8, 64x64x64 tile 8x4x8,\n"
            "//   32x64x32 tile 8x8x4, 64x32x64 tile 4x8x8\n"
            "// with unrelated heap-allocation noise injected between every call.\n"
            "// Usage: ./aarch64_matmul_tile_candidate_mixed_stress_test [cycles]"
        ),
    )
    body += COMMON_DECLS
    body += candidate_extern_decls(candidates)
    body += "\n}\n"
    body += COMMON_HELPERS
    body += """
namespace {

std::vector<Candidate> buildTable() {
  std::vector<Candidate> table;
""" + candidate_table_entries(candidates) + """
  return table;
}

const Candidate& lookup(const std::vector<Candidate>& table, const std::string& shapeKey, const std::string& tileKey) {
  for (const auto& c : table) {
    if (c.shapeKey == shapeKey && c.tileKey == tileKey) return c;
  }
  std::fprintf(stderr, "fatal: missing candidate %s %s\\n", shapeKey.c_str(), tileKey.c_str());
  std::exit(2);
}

}  // namespace

int main(int argc, char** argv) {
  int64_t cycles = argc > 1 ? std::atoll(argv[1]) : 200;
  std::vector<Candidate> table = buildTable();

  // The exact 5-step sequence from the task brief.
  struct Step { std::string shape; std::string tile; };
  std::vector<Step> sequence = {
    {"16x16x16", "tm4_tn4_tk4"},
    {"32x32x32", "tm4_tn8_tk8"},
    {"64x64x64", "tm8_tn4_tk8"},
    {"32x64x32", "tm8_tn8_tk4"},
    {"64x32x64", "tm4_tn8_tk8"},
  };

  int64_t totalCalls = 0;
  int64_t firstFailCycle = -1;
  int firstFailStep = -1;
  double firstFailErr = 0.0;

  for (int64_t cycle = 0; cycle < cycles && firstFailCycle == -1; ++cycle) {
    for (size_t step = 0; step < sequence.size(); ++step) {
      const Candidate& c = lookup(table, sequence[step].shape, sequence[step].tile);

      size_t noise = static_cast<size_t>(16 + (cycle * 7 + step * 13) % 512);
      std::vector<char> churn(noise, static_cast<char>(cycle + step));

      std::vector<float> lhs(static_cast<size_t>(c.m * c.k)), rhs(static_cast<size_t>(c.k * c.n)),
          bias(static_cast<size_t>(c.m * c.n)), ref(static_cast<size_t>(c.m * c.n));
      fillDeterministic(lhs.data(), c.m * c.k, 0x1234u + static_cast<uint32_t>(c.m));
      fillDeterministic(rhs.data(), c.k * c.n, 0x5678u + static_cast<uint32_t>(c.n));
      fillDeterministic(bias.data(), c.m * c.n, 0x9abcu + static_cast<uint32_t>(c.k));
      scalarRef(lhs.data(), rhs.data(), bias.data(), ref.data(), c.m, c.n, c.k);

      MemRef2D lhsDesc = makeDescriptor(lhs.data(), c.m, c.k);
      MemRef2D rhsDesc = makeDescriptor(rhs.data(), c.k, c.n);
      MemRef2D biasDesc = makeDescriptor(bias.data(), c.m, c.n);

      MemRef2D out{};
      c.fn(&out, &lhsDesc, &rhsDesc, &biasDesc);
      double maxErr = 0.0;
      for (int64_t i = 0; i < c.m * c.n; ++i) {
        maxErr = std::max(maxErr, static_cast<double>(std::fabs(out.aligned[i] - ref[static_cast<size_t>(i)])));
      }
      totalCalls++;
      if (maxErr >= 1e-3 && firstFailCycle == -1) {
        firstFailCycle = cycle;
        firstFailStep = static_cast<int>(step);
        firstFailErr = maxErr;
      }
      std::free(out.allocated);
      (void)churn;
    }
  }

  if (firstFailCycle == -1) {
    std::printf("PASS: %lld cycles (%lld total calls) all correct\\n", (long long)cycles, (long long)totalCalls);
    return 0;
  }
  std::printf("FAIL: cycle=%lld step=%d maxErr=%.6f (call #%lld)\\n",
              (long long)firstFailCycle, firstFailStep, firstFailErr, (long long)totalCalls);
  return 1;
}
"""
    return body


def gen_benchmark(candidates):
    body = HEADER_COMMON.format(
        fname="aarch64_matmul_tile_candidate_benchmark.cpp",
        purpose=(
            "Per-shape benchmark: times every tile candidate for one shape (all\n"
            "// linked into this one binary), plus the scalar C++ reference. Generic,\n"
            "// handwritten, and fully-unrolled baselines are measured separately by\n"
            "// the existing mlir_passes/tools/aarch64_matmul_bias_relu_tiled_harness.cpp\n"
            "// (unchanged) -- not duplicated here.\n"
            "// Usage: ./aarch64_matmul_tile_candidate_benchmark <shape MxNxK> <iterations> <warmup>"
        ),
    )
    body += COMMON_DECLS
    body += candidate_extern_decls(candidates)
    body += "\n}\n"
    body += COMMON_HELPERS
    body += """
namespace {

constexpr int64_t kMaxTimedIterations = 20000;

double percentile(std::vector<double> v, double p) {
  std::sort(v.begin(), v.end());
  size_t idx = static_cast<size_t>(p * static_cast<double>(v.size() - 1));
  return v[idx];
}

std::vector<Candidate> buildTable() {
  std::vector<Candidate> table;
""" + candidate_table_entries(candidates) + """
  return table;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 2) {
    std::fprintf(stderr, "usage: %s <shape MxNxK> [iterations] [warmup]\\n", argv[0]);
    return 2;
  }
  std::string shapeKey = argv[1];
  int64_t iterations = argc > 2 ? std::atoll(argv[2]) : 2000;
  int64_t warmup = argc > 3 ? std::atoll(argv[3]) : 200;
  if (iterations > kMaxTimedIterations) iterations = kMaxTimedIterations;

  std::vector<Candidate> table = buildTable();
  std::vector<const Candidate*> matching;
  for (const auto& c : table) if (c.shapeKey == shapeKey) matching.push_back(&c);
  if (matching.empty()) {
    std::fprintf(stderr, "no candidates for shape %s\\n", shapeKey.c_str());
    return 2;
  }

  int64_t M = matching[0]->m, N = matching[0]->n, K = matching[0]->k;
  std::vector<float> lhs(static_cast<size_t>(M * K)), rhs(static_cast<size_t>(K * N)),
      bias(static_cast<size_t>(M * N)), ref(static_cast<size_t>(M * N));
  fillDeterministic(lhs.data(), M * K, 0x1234u + static_cast<uint32_t>(M));
  fillDeterministic(rhs.data(), K * N, 0x5678u + static_cast<uint32_t>(N));
  fillDeterministic(bias.data(), M * N, 0x9abcu + static_cast<uint32_t>(K));
  scalarRef(lhs.data(), rhs.data(), bias.data(), ref.data(), M, N, K);
  MemRef2D lhsDesc = makeDescriptor(lhs.data(), M, K);
  MemRef2D rhsDesc = makeDescriptor(rhs.data(), K, N);
  MemRef2D biasDesc = makeDescriptor(bias.data(), M, N);

  // Scalar reference timing.
  std::vector<double> scalarTimes(static_cast<size_t>(iterations));
  std::vector<float> scratch(static_cast<size_t>(M * N));
  for (int64_t i = 0; i < warmup; ++i) scalarRef(lhs.data(), rhs.data(), bias.data(), scratch.data(), M, N, K);
  for (int64_t i = 0; i < iterations; ++i) {
    auto t0 = std::chrono::steady_clock::now();
    scalarRef(lhs.data(), rhs.data(), bias.data(), scratch.data(), M, N, K);
    auto t1 = std::chrono::steady_clock::now();
    scalarTimes[static_cast<size_t>(i)] = std::chrono::duration<double, std::milli>(t1 - t0).count();
  }
  double scalarMedian = percentile(scalarTimes, 0.5);

  std::printf("{\\n");
  std::printf("  \\"shape\\": \\"%s\\",\\n", shapeKey.c_str());
  std::printf("  \\"M\\": %lld, \\"N\\": %lld, \\"K\\": %lld,\\n", (long long)M, (long long)N, (long long)K);
  std::printf("  \\"iterations\\": %lld,\\n", (long long)iterations);
  std::printf("  \\"scalar_median_ms\\": %.6f,\\n", scalarMedian);
  std::printf("  \\"candidates\\": [\\n");
  for (size_t idx = 0; idx < matching.size(); ++idx) {
    const Candidate* c = matching[idx];
    MemRef2D out{};
    c->fn(&out, &lhsDesc, &rhsDesc, &biasDesc);
    double maxErr = 0.0;
    for (int64_t i = 0; i < M * N; ++i) {
      maxErr = std::max(maxErr, static_cast<double>(std::fabs(out.aligned[i] - ref[static_cast<size_t>(i)])));
    }
    bool correct = maxErr < 1e-3;
    std::free(out.allocated);

    std::vector<double> times(static_cast<size_t>(iterations));
    for (int64_t i = 0; i < warmup; ++i) {
      MemRef2D o{};
      c->fn(&o, &lhsDesc, &rhsDesc, &biasDesc);
      std::free(o.allocated);
    }
    for (int64_t i = 0; i < iterations; ++i) {
      auto t0 = std::chrono::steady_clock::now();
      MemRef2D o{};
      c->fn(&o, &lhsDesc, &rhsDesc, &biasDesc);
      auto t1 = std::chrono::steady_clock::now();
      times[static_cast<size_t>(i)] = std::chrono::duration<double, std::milli>(t1 - t0).count();
      std::free(o.allocated);
    }
    double median = percentile(times, 0.5);
    double p95 = percentile(times, 0.95);

    std::printf("    {\\"tile\\": \\"%s\\", \\"tm\\": %d, \\"tn\\": %d, \\"tk\\": %d, \\"correct\\": %s, \\"max_abs_error\\": %.8f, \\"median_ms\\": %.6f, \\"p95_ms\\": %.6f}%s\\n",
                c->tileKey.c_str(), c->tm, c->tn, c->tk, correct ? "true" : "false", maxErr, median, p95,
                idx + 1 < matching.size() ? "," : "");
  }
  std::printf("  ]\\n");
  std::printf("}\\n");
  return 0;
}
"""
    return body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidates", required=True)
    ap.add_argument("--output-dir", required=True)
    args = ap.parse_args()

    data = json.load(open(args.candidates))
    candidates = [c for c in data["candidates"] if c["legality"]["legal"] and "object_name" in c]

    files = {
        "aarch64_matmul_tile_candidate_repeated_call_test.cpp": gen_repeated_call_test(candidates),
        "aarch64_matmul_tile_candidate_mixed_stress_test.cpp": gen_mixed_stress_test(candidates),
        "aarch64_matmul_tile_candidate_benchmark.cpp": gen_benchmark(candidates),
    }
    import os
    os.makedirs(args.output_dir, exist_ok=True)
    for fname, content in files.items():
        path = os.path.join(args.output_dir, fname)
        with open(path, "w") as f:
            f.write(content)
        print(f"wrote {path} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
